### ISSUE TITLE
How about using metaphlan2 in meta-transcriptome?

### ISSUE THREAD

**Issue by Shicheng-Guo** [boulund/metaphlan2_scripts#1]
Dear Fredrik, 

Do you think we can use metaphlan2 in meta-transcriptome?

Thanks.

Shicheng

**Comment by boulund** [comment]
According to Nicola Segata (one of the MPA2 authors) it is not the best choice to do that, no. He recommends you try using [HUMAnN2](http://huttenhower.sph.harvard.edu/humann2) instead.

https://groups.google.com/forum/#!topic/metaphlan-users/CgCNAG4Iu10
